version: '3.8'
services:
  api-server:
    build: api-server
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://localhost:27017
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=kunlulukun
      - MYSQL_PWD=1016
      - MYSQL_DB=footbook
    depends_on:
      - mongo
      - mysql
  frontend:
    build: frontend
    ports:
      - "3000:80"
    depends_on:
      - api-server
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "footbook"
      MYSQL_USER: "kunlulukun"
      MYSQL_PASSWORD: "1016"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"